version: '3.8'

networks:
    app-network:
        driver: bridge

volumes:
    app-data:

services:
    webserver:
        image: nginx:1.21.6-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "42080:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            app-network:

    mysql:
        container_name: fast_test_db
        image: mysql/mysql-server:8.0
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            app-network:
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
            - ./.docker/mysql/init.sh:/docker-entrypoint-initdb.d/create-testing-database.sh
    backend:
        build:
            context: .
        extra_hosts:
            -   "host.docker.internal:host-gateway"
        container_name: backend
        depends_on:
            - mysql
            - webserver
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
            - .docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            app-network:


